### ISSUE TITLE
Extract additional description

### ISSUE THREAD

**Issue by vkhizanov** [sergliashenko/ParserUpWork#13]
Implement a function which determines if additional job description is available and returns it in some form (e.g. plain text, link etc) if possible.
```python
def get_additional_info(json_data: dict) -> List[str]:
    """
    Returns a list of links.
    """
    pass
```

**Comment by zloyvetal** [comment]
def get_additional_info(json_data: dict) -> typing.Union[list, None]:
    """
    Returns a list of links.
    """
    if "Job details" not in json_data:
        return None

    our_string = json_data["Job details"]

    list_with_info = re.findall('http[s]?://(?:[a-zA-Z]|[0-9]|[$-_@.&+]|[!*\(\),]|(?:%[0-9a-fA-F][0-9a-fA-F]))+',
                                our_string)

    return list_with_info
