### ISSUE TITLE
Extract keywords in capital case

### ISSUE THREAD

**Issue by vkhizanov** [sergliashenko/ParserUpWork#20]
Compile a list of keywords in capital case and implement a function which extracts such words from job description.
```python
def get_keywords_capital(job_desc: dict, keywords_capital_list: List[str]) -> List[str]
```

**Comment by skondrat** [comment]
['COST', 'ONLY', 'DESIGN', 'QUALITY:','BEFORE', 'GOOD', 'PERSON', 'QUICKLY','IMPORTANT', 'BS', 'PROVIDE', 'NEEDED', 'TIMELINE', 'FINANCIAL', 'REQUIRED', 'NDA', 'URGENT', 'NOT', 'SKILLS', 'R&D', 'QUALIFICATIONS, 'APPLY','USD', 'AI/ML', 'REAL', 'CLI', 'WEBSITES, 'IMMEDIATELY', 'UNIQUE', 'ASAP', 'KNOWLEDGE', 'CONFIDENTIALITY', 'AGREEMENT', 'AI', 'INDIA', 'ML', 'ADEPT', 'IMPORTANT', 'MVP', 'COMMUNICATION', 'DICOM', 'STRONG', 'NECESSARY, 'BANGLADESH!!!', 'PREFERRED', 'ACCEPTABLE', 'DISQUALIFIED', 'BANGALORE', 'TIME', 'REQUIREMENTS', 'NEED', 'US', 'BONUS:', 'DESIRED', 'NEEDED:', 'RESPONSIBILITIES', 'REQUIRE', 'NLP', "DON'T"]
