### ISSUE TITLE
Extract skills

### ISSUE THREAD

**Issue by vkhizanov** [sergliashenko/ParserUpWork#4]
Implement a function which takes job description in JSON format and outputs a list of **normalized** skills found in the description. Write a unit test for it.
```python
from typing import List
def get_skills(job_desc: dict) -> List[str]:
    pass
```

**Comment by sergliashenko** [comment]
We have function like this.
features.py -> get_job_skills

**Comment by sergliashenko** [comment]
And we have to function which develop Vitaliy, which parse field "Details" and get Skills.

**Comment by vkhizanov** [comment]
This way either rename the function in code or make a comment here and close an issue.

**Comment by sergliashenko** [comment]
1)Get skills from field "Other skills"
https://github.com/sergliashenko/ParserUpWork/blob/master/src/features.py#L239
2)Get skills from JSON by parsing the text
https://github.com/sergliashenko/ParserUpWork/blob/master/src/features.py#L109
This ticket can be closed

**Comment by vkhizanov** [comment]
https://github.com/sergliashenko/ParserUpWork/blob/master/src/resources/skills.json
this file should be populated with more skills. The compilation of relevant skills will be provided by sales managers in the near future.
