### ISSUE TITLE
Extract # of freelancers to hire

### ISSUE THREAD

**Issue by vkhizanov** [sergliashenko/ParserUpWork#5]
Implement a function which takes job description in JSON format and outputs a number of freelancers to hire (or `1` if not specified). Write a unit test for it.
```python
def get_n_of_freelancers(job_desc: dict) -> int:
    pass
```

**Comment by sergliashenko** [comment]
Please see function below:
features.py->get_client_history 
You mean function like this?

**Comment by sergliashenko** [comment]
Or number of freelancers which hire on the one project?

**Comment by sergliashenko** [comment]
https://github.com/sergliashenko/ParserUpWork/blob/6b3d6c800e4c5dd1411a023bb45dc7de41f5268e/src/features.py#L354
