### ISSUE TITLE
Extract customer's country

### ISSUE THREAD

**Issue by vkhizanov** [sergliashenko/ParserUpWork#6]
Implement a function which takes job description in JSON format and outputs a string with **normalized** customer's country. Write a unit test for it.
```python
def get_country(job_desc: dict) -> str:
    pass
```

**Comment by sergliashenko** [comment]
https://github.com/sergliashenko/ParserUpWork/blob/6b3d6c800e4c5dd1411a023bb45dc7de41f5268e/src/features.py#L373
