### ISSUE TITLE
Extract hourly or fixed price payment

### ISSUE THREAD

**Issue by vkhizanov** [sergliashenko/ParserUpWork#7]
Implement a function which takes job description in JSON format and outputs a string which can be either `fixed price` or `hourly rate` .
```python
from typing import Tuple, Union
def get_hourly_or_fixed(job_desc: dict) -> Union[str, None]:
    pass
```

**Comment by sergliashenko** [comment]
At now we have functions:
get_job_type return "Hourly" or "Fixed Price" and function get_avg_hourly_rate return average price how much does the customer pay.

And we can merge this two function in one get_budget_info.
I understand correctly?

**Comment by zloyvetal** [comment]
we have two functions -> get_fixed_price and get_filter_of_fixed_or_hourly
