### ISSUE TITLE
Extract sign up date

### ISSUE THREAD

**Issue by vkhizanov** [sergliashenko/ParserUpWork#9]
Implement a function which takes job description in JSON format and outputs customer's sign up date. Write a unit test for it.
```python
from datetime import datetime
def get_signup_date(job_desc: dict) -> datetime:
    pass
```

**Comment by sergliashenko** [comment]
https://github.com/sergliashenko/ParserUpWork/blob/6b3d6c800e4c5dd1411a023bb45dc7de41f5268e/src/features.py#L390

But return type in my function is "date" not is "datetime"
